apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
      - name: springboot-backend
        image: us-central1-docker.pkg.dev/sonneurs-juvi-dev/backend-repo/springboot-backend:latest
        env:
        - name: DB_HOST
          value: "127.0.0.1"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: springboot-secret
              key: DB_NAME
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: springboot-secret
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: springboot-secret
              key: DB_PASSWORD
        ports:
        - containerPort: 8080

      - name: cloud-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.37.5-bullseye

        command:
          - "/cloud_sql_proxy"
          - "-instances=sonneurs-juvi-dev:us-central1:instance-postgres=tcp:0.0.0.0:5432"
          - "-credential_file=/secrets/cloudsql/credentials.json"
        volumeMounts:
        - name: cloudsql-instance-credentials
          mountPath: /secrets/cloudsql
          readOnly: true

      volumes:
      - name: cloudsql-instance-credentials
        secret:
          secretName: springboot-service-account-key