spring:
  datasource:
    url: jdbc:postgresql:///sonneursdb?cloudSqlInstance=${INSTANCE_CONNECTION_NAME}&socketFactory=com.google.cloud.sql.postgres.SocketFactory
    username: svc-app-son-user
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver





