runtime: custom
env: flex

service: default

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
  cpu_utilization:
    target_utilization: 0.6

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

env_variables:
  SPRING_PROFILES_ACTIVE: ${ENVIRONMENT}
  SPRING_DATASOURCE_URL: jdbc:postgresql:///${DB_NAME}?cloudSqlInstance=${INSTANCE_CONNECTION_NAME}&socketFactory=com.google.cloud.sql.postgres.SocketFactory
  SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
  SPRING_DATASOURCE_PASSWORD: $DB_PASSWORD

runtime_config:
  jvm: openjdk17
  artifact: target/app.jar

beta_settings:
  cloud_sql_instances: ${INSTANCE_CONNECTION_NAME}
