name: Deploy to Cloud Run

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Charger variables env
        run: |
          source deploy/env/env.${{ github.event.inputs.environment }}
          echo "GCP_PROJECT=$GCP_PROJECT" >> $GITHUB_ENV
          echo "DB_NAME=$DB_NAME" >> $GITHUB_ENV
          echo "..." # ajoute toutes les autres

      - name: Authentification
        run: |
          echo "${{ secrets.GCP_CREDENTIALS }}" | base64 --decode > gcp-key.json
          gcloud auth activate-service-account --key-file=gcp-key.json
          gcloud config set project "$GCP_PROJECT"

      - name: Deploy Cloud Run
        run: |
          gcloud run deploy springboot-backend \
            --image=$DOCKER_IMAGE \
            --region=us-central1 \
            --platform=managed \
            --allow-unauthenticated \
            --timeout=600s \
            --set-env-vars DB_NAME=$DB_NAME,DB_USERNAME=$DB_USERNAME