name: Deploy to Cloud Run

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        options: [dev, prod]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Auth GCP
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: |
          echo "${GCP_CREDENTIALS}" | base64 --decode > gcp-key.json
          gcloud auth activate-service-account --key-file=gcp-key.json
          gcloud config set project sonneurs-juvi-${{ github.event.inputs.environment }}

      - name: Load environment variables
        run: |
          cp .github/env.${{ github.event.inputs.environment }} .env
          export $(grep -v '^#' .env | xargs)

      - name: Deploy to Cloud Run
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          gcloud run deploy springboot-backend \
            --image=us-central1-docker.pkg.dev/sonneurs-juvi-${{ github.event.inputs.environment }}/backend-repo/springboot-backend \
            --platform=managed \
            --region=us-central1 \
            --allow-unauthenticated \
            --timeout=600s \
            --set-env-vars DB_NAME=${DB_NAME} \
            --set-env-vars DB_USERNAME=${DB_USERNAME} \
            --set-env-vars DB_PASSWORD=${DB_PASSWORD} \
            --set-env-vars INSTANCE_CONNECTION_NAME=${INSTANCE_CONNECTION_NAME}
