name: Deploy to GKE

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        options: [dev, prod]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to GCP and get GKE credentials
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: |
          echo "$GCP_CREDENTIALS" | base64 --decode > gcp-key.json
          gcloud auth activate-service-account --key-file=gcp-key.json
          gcloud config set project sonneurs-juvi-${{ github.event.inputs.environment }}
          gcloud container clusters get-credentials my-cluster --zone us-central1-a

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yml
