name: Deploy to Compute Engine (VM)

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        options: [dev, prod]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: |
          echo "$GCP_CREDENTIALS" | base64 --decode > gcp-key.json
          gcloud auth activate-service-account --key-file=gcp-key.json
          gcloud config set project sonneurs-juvi-${{ github.event.inputs.environment }}

      - name: Copy JAR to VM and restart service
        run: |
          gcloud compute scp target/*.jar my-vm-user@my-vm-name:/home/my-vm-user/app.jar \
            --zone=us-central1-a \
            --quiet
          gcloud compute ssh my-vm-user@my-vm-name --zone=us-central1-a \
            --command="sudo systemctl restart my-app"
