name: Build and Test Backend

on:
  push:
    branches:
      - main
      - moha-sonneur1
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Build with Maven
        run: mvn clean install -DskipTests=true

      # - name: Deploy to GCP (Cloud Run, GKE, etc.)
      - name: Generate fat jar
        run: mvn clean package spring-boot:repackage -DskipTests=true

      - name: Upload jar to GCS
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: |
          echo "${GCP_CREDENTIALS}" | base64 --decode  > gcp-key.json
          gcloud auth activate-service-account --key-file=gcp-key.json
          gcloud config set project sonneurs-juvi-dev
          gsutil cp target/*.jar gs://sonneurs-docs-2025/jars/
      - name: Build & Push Docker Image to Artifact Registry
        run: |
         gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
         docker build -t us-central1-docker.pkg.dev/sonneurs-juvi-dev/backend-repo/springboot-backend .
         docker push us-central1-docker.pkg.dev/sonneurs-juvi-dev/backend-repo/springboot-backend
         
  #   - name: Deploy to Cloud Run
  #     run: |
  #       gcloud run deploy springboot-backend \
  #         --image=us-central1-docker.pkg.dev/sonneurs-juvi-dev/backend-repo/springboot-backend \
  #         --platform=managed \
  #         --region=us-central1 \
  #         --allow-unauthenticated \
  #         --timeout=600s \
  #         --set-env-vars DB_NAME=sonneursdb \
  #         --set-env-vars DB_USERNAME=svc-app-son-user \
  #         --set-env-vars DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
  #         --set-env-vars INSTANCE_CONNECTION_NAME=sonneurs-juvi-dev:us-central1:instance-postgres
      - name: Deploy to App Engine Flexible
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: |
          echo "${GCP_CREDENTIALS}" | base64 --decode > gcp-key.json
          gcloud auth activate-service-account --key-file=gcp-key.json
          gcloud config set project sonneurs-juvi-dev
          gcloud services enable cloudresourcemanager.googleapis.com appengine.googleapis.com
          gcloud config set app/cloud_build_timeout 1600
          gcloud app deploy --quiet --verbosity=info app.yml
